# Generated by Django 4.2.5 on 2023-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_category_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='retal_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
